name: ${name}
version: ${describe}
description: ${description}
author: Barteks2x
main: org.barteks2x.minielementgaming.Plugin
depend: [WorldEdit]
loadbefore: [WorldEdit]
commands:
  db:
    description: Make arena
    usage: |
        Use /db help <subcommand> [<subcommand2>] or /mghelp for more information
        <something> - required parameter
        [<something>] - optional parameter
        /db reload-config OR rc - reload minigame config
        /db automake <TEAM1-COLOR:TEAM2-COLOR> <name> <floor-id>[:<meta>] 
            <wall-id1>[:<meta>] <wall-id2>[:<meta>] <line-id>[:<meta>] height - 
                  build arena in worldedit selection. Example: 
                  /db arena autobuild minigame1 /db 5:3 35:11 20 89 3
        /db save <minigame-name> [<on-start-auto-rebuild(true/false)>] - save current arena state (minigame MUST be created)
        /db delete <name>
        /db start <name>
        /db stop <name>
        /db kickplayer <minigame-name> <player>
        /db join <name> - join minigame
        /db leave - leave minigame
    permission: minigame
  dbhelp:
    description: Minigame halp
    usage: /dbhelp [<subcommand1>] [<subcommand2>]
permissions:
  db.admin:
    decription: Gives access to all commands recommended for admins (except reload)
    children:
      db.delete: true
      db.start: true
      db.stop: true
      db.player.*: true
      db.help.*: true
  db.*:
    description: Gives access to all dodgeball commands
    children:
      db.reload: true
      db.delete: true
      db.start: true
      db.stop: true
      db.player.*: true
      db.help.*: true
  db.reload:
    description: Gives access to reload dodgeball configuration
  db.automake:
    description: Gives access to /db autobuild
  db.save:
    description: Gives access to /db savestate
  db.delete: 
    description: Gives access to /db delete
  db.start: 
    description: Gives access to /db start
  db.stop: 
    description: Gives access to /db stop
  db.player.*:
    description: Gives access to all commands recommended for players
    children:
      db.join: true
      db.leave: true
      db.help.player: true
  db.join:
    description: Gives access to /db join (/join)
  db.leave:
    description: Gives access to /db leave (/leave)
  db.help.*:
    description: Minigame help commands
    children:
      db.help.admin: true
  db.help.player:
    description: Minigame help for players (only player commands)
  db.help.admin:
    description: Minigame help for admins (all commands)
    children:
      db.help.player: true