name: MiniElementGaming
version: "93dd148"
description: Plugin for MiniElementGaming Minecraft server
authors: ['Barteks2x']
main: org.barteks2x.minielementgaming.Plugin
commands:
  makearena:
    description: Make arena